export const AGRIC_LIST_REQUEST = "AGRIC_LIST_REQUEST"
export const AGRIC_LIST_SUCCESS = "AGRIC_LIST_SUCCESS"
export const AGRIC_LIST_FAIL = "AGRIC_LIST_FAIL"

export const AGRIC_DETAILS_REQUEST = "AGRIC_DETAILS_REQUEST"
export const AGRIC_DETAILS_SUCCESS = "AGRIC_DETAILS_SUCCESS"
export const AGRIC_DETAILS_FAIL = "AGRIC_DETAILS_FAIL"

export const CREATE_AGRIC_REQUEST = "CREATE_AGRIC_REQUEST"
export const CREATE_AGRIC_SUCCESS = "CREATE_AGRIC_SUCCESS"
export const CREATE_AGRIC_FAIL = "CREATE_AGRIC_FAIL"
export const CREATE_AGRIC_RESET = "CREATE_AGRIC_RESET"


export const UPDATE_AGRIC_REQUEST = "UPDATE_AGRIC_REQUEST"
export const UPDATE_AGRIC_SUCCESS = "UPDATE_AGRIC_SUCCESS"
export const UPDATE_AGRIC_FAIL = "UPDATE_AGRIC_FAIL"
export const UPDATE_AGRIC_RESET = "UPDATE_AGRIC_RESET"


export const DELETE_AGRIC_REQUEST = "DELETE_AGRIC_REQUEST"
export const DELETE_AGRIC_SUCCESS = "DELETE_AGRIC_SUCCESS"
export const DELETE_AGRIC_FAIL = " DELETE_AGRIC_FAIL"


export const AGRIC_CREATE_REVIEW_REQUEST = 'AGRIC_CREATE_REVIEW_REQUEST'
export const AGRIC_CREATE_REVIEW_SUCCESS = 'AGRIC_CREATE_REVIEW_SUCCESS'
export const AGRIC_CREATE_REVIEW_FAIL = 'AGRIC_CREATE_REVIEW_FAIL'
export const AGRIC_CREATE_REVIEW_RESET = 'AGRIC_CREATE_REVIEW_RESET'
