export const AGRIC_CART_ADD_ITEM = "AGRIC_CART_ADD_ITEM"
export const NATURAL_CART_ADD_ITEM = "NATURAL_CART_ADD_ITEM"
export const ICT_CART_ADD_ITEM = "ICT_CART_ADD_ITEM"
export const AGRIC_CART_REMOVE_ITEM = "AGRIC_CART_REMOVE_ITEM"

export const AGRIC_CART_SAVE_SHIPPING_ADDRESS = 'AGRIC_CART_SAVE_SHIPPING_ADDRESS'

export const AGRIC_CART_SAVE_PAYMENT_METHOD = 'AGRIC_CART_SAVE_PAYMENT_METHOD'

export const AGRIC_CART_CLEAR_ITEMS = 'AGRIC_CART_CLEAR_ITEMS'