export const BLOG_LIST_REQUEST = "BLOG_LIST_REQUEST"
export const BLOG_LIST_SUCCESS = "BLOG_LIST_SUCCESS"
export const BLOG_LIST_FAIL = "BLOG_LIST_FAIL"



export const BLOG_DETAILS_REQUEST = "BLOG_DETAILS_REQUEST"
export const BLOG_DETAILS_SUCCESS = "BLOG_DETAILS_SUCCESS"
export const BLOG_DETAILS_FAIL = "BLOG_DETAILS_FAIL"


export const CREATE_BLOG_REQUEST = "CREATE_BLOG_REQUEST"
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS"
export const CREATE_BLOG_FAIL = "CREATE_BLOG_FAIL"
export const CREATE_BLOG_RESET = "CREATE_BLOG_RESET"


export const UPDATE_BLOG_REQUEST = "UPDATE_BLOG_REQUEST"
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS"
export const UPDATE_BLOG_FAIL = "UPDATE_BLOG_FAIL"
export const UPDATE_BLOG_RESET = "UPDATE_BLOG_RESET"


export const DELETE_BLOG_REQUEST = "DELETE_BLOG_REQUEST"
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS"
export const DELETE_BLOG_FAIL = " DELETE_BLOG_FAIL"


export const BLOG_CREATE_REVIEW_REQUEST = 'BLOG_CREATE_REVIEW_REQUEST'
export const BLOG_CREATE_REVIEW_SUCCESS = 'BLOG_CREATE_REVIEW_SUCCESS'
export const BLOG_CREATE_REVIEW_FAIL = 'BLOG_CREATE_REVIEW_FAIL'
export const BLOG_CREATE_REVIEW_RESET = 'BLOG_CREATE_REVIEW_RESET'



