export const ICT_LIST_REQUEST = "ICT_LIST_REQUEST"
export const ICT_LIST_SUCCESS = "ICT_LIST_SUCCESS"
export const ICT_LIST_FAIL = "ICT_LIST_FAIL"

export const ICT_DETAILS_REQUEST = "ICT_DETAILS_REQUEST"
export const ICT_DETAILS_SUCCESS = "ICT_DETAILS_SUCCESS"
export const ICT_DETAILS_FAIL = "ICT_DETAILS_FAIL"

export const CREATE_ICT_REQUEST = "CREATE_ICT_REQUEST"
export const CREATE_ICT_SUCCESS = "CREATE_ICT_SUCCESS"
export const CREATE_ICT_FAIL = "CREATE_ICT_FAIL"
export const CREATE_ICT_RESET = "CREATE_ICT_RESET"


export const UPDATE_ICT_REQUEST = "UPDATE_ICT_REQUEST"
export const UPDATE_ICT_SUCCESS = "UPDATE_ICT_SUCCESS"
export const UPDATE_ICT_FAIL = "UPDATE_ICT_FAIL"
export const UPDATE_ICT_RESET = "UPDATE_ICT_RESET"


export const DELETE_ICT_REQUEST = "DELETE_ICT_REQUEST"
export const DELETE_ICT_SUCCESS = "DELETE_ICT_SUCCESS"
export const DELETE_ICT_FAIL = " DELETE_ICT_FAIL"


export const ICT_CREATE_REVIEW_REQUEST = 'ICT_CREATE_REVIEW_REQUEST'
export const ICT_CREATE_REVIEW_SUCCESS = 'ICT_CREATE_REVIEW_SUCCESS'
export const ICT_CREATE_REVIEW_FAIL = 'ICT_CREATE_REVIEW_FAIL'
export const ICT_CREATE_REVIEW_RESET = 'ICT_CREATE_REVIEW_RESET'