export const NATURAL_LIST_REQUEST = "NATURAL_LIST_REQUEST"
export const NATURAL_LIST_SUCCESS = "NATURAL_LIST_SUCCESS"
export const NATURAL_LIST_FAIL = "NATURAL_LIST_FAIL"

export const NATURAL_DETAILS_REQUEST = "NATURAL_DETAILS_REQUEST"
export const NATURAL_DETAILS_SUCCESS = "NATURAL_DETAILS_SUCCESS"
export const NATURAL_DETAILS_FAIL = "NATURAL_DETAILS_FAIL"

export const CREATE_NATURAL_REQUEST = "CREATE_NATURAL_REQUEST"
export const CREATE_NATURAL_SUCCESS = "CREATE_NATURAL_SUCCESS"
export const CREATE_NATURAL_FAIL = "CREATE_NATURAL_FAIL"
export const CREATE_NATURAL_RESET = "CREATE_NATURAL_RESET"


export const UPDATE_NATURAL_REQUEST = "UPDATE_NATURAL_REQUEST"
export const UPDATE_NATURAL_SUCCESS = "UPDATE_NATURAL_SUCCESS"
export const UPDATE_NATURAL_FAIL = "UPDATE_NATURAL_FAIL"
export const UPDATE_NATURAL_RESET = "UPDATE_NATURAL_RESET"


export const DELETE_NATURAL_REQUEST = "DELETE_NATURAL_REQUEST"
export const DELETE_NATURAL_SUCCESS = "DELETE_NATURAL_SUCCESS"
export const DELETE_NATURAL_FAIL = " DELETE_NATURAL_FAIL"

export const NATURAL_CREATE_REVIEW_REQUEST = 'NATURAL_CREATE_REVIEW_REQUEST'
export const NATURAL_CREATE_REVIEW_SUCCESS = 'NATURAL_CREATE_REVIEW_SUCCESS'
export const NATURAL_CREATE_REVIEW_FAIL = 'NATURAL_CREATE_REVIEW_FAIL'
export const NATURAL_CREATE_REVIEW_RESET = 'NATURAL_CREATE_REVIEW_RESET'

