# Generated by Django 3.1.2 on 2021-11-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='promotion',
            fields=[
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
                ('dayToUse', models.CharField(blank=True, max_length=200, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='informationtechproduct',
            name='numReviews',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informationtechproduct',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='naturalproduct',
            name='numReviews',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='naturalproduct',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
