# Generated by Django 3.1.2 on 2021-11-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0002_auto_20211126_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewagric',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewict',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewnatural',
            name='user',
        ),
        migrations.AddField(
            model_name='reviewagric',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reviewict',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reviewnatural',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
