# Generated by Django 3.1.2 on 2021-11-26 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0003_auto_20211126_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewnatural',
            old_name='AgricProduct',
            new_name='naturalproduct',
        ),
    ]
