# Generated by Django 3.1.2 on 2021-12-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0008_order_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationtechproduct',
            name='stocks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
