# Generated by Django 3.1.2 on 2021-12-22 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0009_informationtechproduct_stocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('qty', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='milestone.order')),
                ('productAgric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='milestone.agricproduct')),
                ('productInformation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='milestone.informationtechproduct')),
                ('productNatural', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='milestone.naturalproduct')),
            ],
        ),
    ]
